
// This file has been generated by the GUI designer. Do not modify.
namespace AdaShell
{
	public partial class DownloadDialog
	{
		private global::Gtk.Fixed fixed4;
		private global::Gtk.ProgressBar progressBar;
		private global::Gtk.Label activityLabel;
		private global::Gtk.Button buttonCancel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget AdaShell.DownloadDialog
			this.Name = "AdaShell.DownloadDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Download");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child AdaShell.DownloadDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.progressBar = new global::Gtk.ProgressBar ();
			this.progressBar.WidthRequest = 300;
			this.progressBar.Name = "progressBar";
			this.progressBar.Text = global::Mono.Unix.Catalog.GetString ("0%");
			this.progressBar.PulseStep = 0.01;
			this.fixed4.Add (this.progressBar);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.progressBar]));
			w2.X = 60;
			w2.Y = 30;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.activityLabel = new global::Gtk.Label ();
			this.activityLabel.Name = "activityLabel";
			this.activityLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("toto");
			this.fixed4.Add (this.activityLabel);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.activityLabel]));
			w3.X = 60;
			w3.Y = 95;
			w1.Add (this.fixed4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed4]));
			w4.Position = 0;
			// Internal child AdaShell.DownloadDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonCancel]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 447;
			this.DefaultHeight = 211;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnClickedCancelButton);
		}
	}
}
